version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    environment:
      #            Fixes bug where websocket connection is fixed to default port 3000
      - WDS_SOCKET_PORT=0
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ['npm','run','test']